### ISSUE TITLE
Conform to ESLint's plugin API

### ISSUE THREAD

**Issue by tlvince** [Gillespie59/angularjs-eslint#5]
Currently, to make use of this, you have to manually handle ESLint's `--rules-dir` option.

As of [v0.8.0](http://eslint.org/blog/2014/09/eslint-0.8.0-released/), ESLint received proper support for plugins.

To be able to load this plugin automatically, a few amendments need to be made:

* Rename the plugin to `eslint-plugin-angularjs` (you might consider starting afresh to avoid the extra weight of [node_modules](https://github.com/Gillespie59/angularjs-eslint/pull/1) in the history and adding a deprecation notice on this repo)
* Add a module that exposes a rule ID -> rule mapping

See [working with plugins](http://eslint.org/docs/developer-guide/working-with-plugins.html) for more. I also recently updated [eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine) which might be helpful.

**Comment by Gillespie59** [comment]
Thanks a lot for this feedback :d. I will work on that very soon.

**Comment by EmmanuelDemey** [comment]
I have just created a new repo here : https://github.com/Gillespie59/eslint-plugin-angularjs

**Comment by EmmanuelDemey** [comment]
Done : https://www.npmjs.com/package/eslint-plugin-angular
Thanks

**Comment by tlvince** [comment]
Great work :+1:
